access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
bucket: <%= ENV['S3_BUCKET'] %>
s3_endpoint:  <%= ENV['s3-eu-west-1.amazonaws.com'] %>
attachment_url:  <%= ENV['s3-eu-west-1.amazonaws.com'] %>
s3_host_alias:  <%= ENV['s3-eu-west-1.amazonaws.com'] %>